# Generated by Django 3.2.16 on 2022-12-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.DateField(default='1998-03-09'),
            preserve_default=False,
        ),
    ]
